<?php $cnt = count($this->getImage()); ?>
<?php if($cnt > 0 ): ?>
	<?php foreach ($this->getImage() as $item): ?>  
    <div class="page-title">
        <h1><?php   echo $item->getTitle(); ?></h1>
    </div>                
	<div class="imageDetail" >
        <img style="float:left; margin:0 10px 10px 0; border-radius: 5px; border:5px solid #a89ca1;" src="<?php echo $this->resizeImage($item->getFilename(), 267, 400, ''); ?>" alt="<?php   echo $item->getTitle(); ?>" />
        <?php echo $item->getContent(); ?>
	</div>  
	<?php endforeach;  ?> 
<?php else: ?>
	<div>There is no Images here</div>
<?php endif; ?>
